version: '3'
services:
  swagger-ui:
    build: ./swagger-ui
    ports:
      - 3200:3200
    volumes:
      - ./swagger-ui/webpack/docker-dev.babel.js:/swagger-ui/webpack/docker-dev.babel.js
      - ./swagger-ui/dev-helpers/index.html:/swagger-ui/dev-helpers/index.html
      - ./swagger-ui/dev-helpers/swagger.yaml:/swagger-ui/dev-helpers/swagger.yaml
    working_dir: /swagger-ui
    command: 'npx webpack-dev-server --config webpack/docker-dev.babel.js'
  watcher:
    build: ./watcher
    volumes:
      - ./watcher:/app
      - /app/node_modules
      - ./src:/src
      - ./swagger-ui/dev-helpers/swagger.yaml:/dist/swagger.yaml
    working_dir: /app
    command: 'node index.js'